"""Create audio collection and records

Revision ID: af5fcad105f3
Revises: 33fff847ef27
Create Date: 2025-11-05 11:09:27.430409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5fcad105f3'
down_revision: Union[str, Sequence[str], None] = '33fff847ef27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_collections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('record_count > 0', name='check_record_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('audio_records',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('record_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['audio_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_records')
    op.drop_table('audio_collections')
    # ### end Alembic commands ###
