"""Add summarization task table

Revision ID: d4819eaf2c37
Revises: c1414a9caac2
Create Date: 2025-11-18 16:01:09.709735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4819eaf2c37'
down_revision: Union[str, Sequence[str], None] = 'c1414a9caac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summarization_tasks',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('waiting_time', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id')
    )
    op.create_table('summary_templates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('md_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('transcriptions',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('segment_duration', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcriptions')
    op.drop_table('summary_templates')
    op.drop_table('summarization_tasks')
    # ### end Alembic commands ###
