"""Add unique constraint in social

Revision ID: a4d3940f622e
Revises: a28bcc0b577d
Create Date: 2025-11-27 13:31:57.204877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d3940f622e'
down_revision: Union[str, Sequence[str], None] = 'a28bcc0b577d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('social_user_id', sa.String(), nullable=False))
    op.create_unique_constraint('social_account_uq', 'social_accounts', ['provider', 'social_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('social_account_uq', 'social_accounts', type_='unique')
    op.drop_column('social_accounts', 'social_user_id')
    # ### end Alembic commands ###
