"""Add new columns for summarization task

Revision ID: 5131f0fb8609
Revises: d4819eaf2c37
Create Date: 2025-11-18 16:03:23.985892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5131f0fb8609'
down_revision: Union[str, Sequence[str], None] = 'd4819eaf2c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summarization_tasks', sa.Column('collection_id', sa.UUID(), nullable=False))
    op.add_column('summarization_tasks', sa.Column('summary_type', sa.String(), nullable=False))
    op.add_column('summarization_tasks', sa.Column('document_format', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summarization_tasks', 'document_format')
    op.drop_column('summarization_tasks', 'summary_type')
    op.drop_column('summarization_tasks', 'collection_id')
    # ### end Alembic commands ###
